routes/web.php
<?php

use App\Http\Controllers\AboutController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\BusController;
use App\Http\Controllers\CarsController;
use App\Http\Controllers\ConditionsController;
use App\Http\Controllers\GaleriController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KontakController;
use App\Http\Controllers\MicesController;
use App\Http\Controllers\MobilController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\TestimoniController;
use App\Http\Controllers\TourCategoriesController;
use App\Http\Controllers\WisataController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('sewa-mobil', [CarsController::class, 'mobil'])->name('sewa-mobil');
Route::get('sewa-bus', [MobilController::class, 'bus'])->name('sewa-bus');

Route::get('paket-wisata', [WisataController::class, 'index'])->name('paket-wisata');
Route::get('wisata/{slug}', [WisataController::class, 'wisata'])->name('wisata');
Route::get('detail-wisata/{slug}', [WisataController::class, 'detail_wisata'])->name('detail-wisata');

Route::get('mice', [MicesController::class, 'mice'])->name('mice');
Route::get('mice-event', [MicesController::class, 'mice_event'])->name('mice-event');

Route::get('blog', [BlogController::class, 'index'])->name('blog');
Route::get('detail-blog/{slug}', [BlogController::class, 'detail_blog'])->name('blog.detail-blog');
// Route::get('detail-blog', [BlogController::class, 'detail_blog'])->name('detail-blog');
Route::get('galeri', [GaleriController::class, 'galeri'])->name('galeri');
Route::get('about', [AboutController::class, 'index'])->name('about');
Route::get('kontak', [KontakController::class, 'index'])->name('kontak');

Route::get('login', [AuthController::class, 'index'])->name('login');
Route::get('register', [AuthController::class, 'register'])->name('register');
Route::post('proses_register', [AuthController::class, 'proses_register'])->name('proses_register');
Route::post('proses_login', [AuthController::class, 'proses_login'])->name('proses_login');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');

Route::get('/register/verify-email/{token}', [AuthController::class, 'verifyMail'])->name('verifyMail');
// Route::resource('admin/dashboard', DashboardController::class);

Route::group(['middleware' => ['auth']], function () {
    Route::prefix('admin/')->name('admin.')->middleware(['admin_role'])->group(function () {
        Route::get('create_tour/{id}', [TourCategoriesController::class, 'create_tour'])->name('tour_categori.create_tour');
        Route::resource('dashboard', DashboardController::class);
        Route::resource('user', UserController::class);
        Route::put('update-password/{userid}', [UserController::class, 'update_password'])->name('user.update-password');
        Route::resource('artikel', ArtikelController::class);
        Route::resource('galeri', GaleriController::class);
        Route::resource('condition', ConditionsController::class);
        Route::put('update_condition', [ConditionsController::class, 'update_condition'])->name('profil.update_condition');
        Route::resource('cars', CarsController::class);
        Route::resource('mobil', MobilController::class);
        Route::resource('profil', ProfilController::class);
        Route::put('update_profil', [ProfilController::class, 'update_profil'])->name('profil.update_profil');
        Route::resource('testimoni', TestimoniController::class);
        Route::resource('mice', MicesController::class);
        Route::put('update_mice', [MicesController::class, 'update_mice'])->name('mice.update_mice');
        Route::resource('tour_categori', TourCategoriesController::class);
        Route::post('store_tour/{id}', [TourCategoriesController::class, 'store_tour'])->name('tour_categori.store_tour');
        Route::get('edit_tour/{id}', [TourCategoriesController::class, 'edit_tour'])->name('tour_categori.edit_tour');
        Route::put('update_tour/{id}', [TourCategoriesController::class, 'update_tour'])->name('tour_categori.update_tour');
        Route::delete('destroy_tour/{id}', [TourCategoriesController::class, 'destroy_tour'])->name('tour_categori.destroy_tour');
        Route::get('destroy_price/{id}', [TourCategoriesController::class, 'destroy_price'])->name('tour_categori.destroy_price');
        Route::get('edit_price/{id}', [TourCategoriesController::class, 'edit_price'])->name('tour_categori.edit_price');
        Route::post('/update_price/{id}', [TourCategoriesController::class, 'update_price'])->name('tour_categori.update_price');
    });
});


Route::prefix('frontend/')->name('frontend.')->group(function () {
    Route::get('home', function () {
        return view('frontend.home');
    });
    Route::get('about', function () {
        return view('frontend.about');
    });
    Route::get('detail_blog', function () {
        return view('frontend.detail_blog');
    });
    Route::get('detail_wisata', function () {
        return view('frontend.detail_wisata');
    });
    Route::get('galeri', function () {
        return view('frontend.galeri');
    });
    Route::get('kontak', function () {
        return view('frontend.kontak');
    });
    Route::get('paket_wisata', function () {
        return view('frontend.paket_wisata');
    });
    Route::get('sewa_bus', function () {
        return view('frontend.sewa_bus');
    });
    Route::get('sewa_mobil', function () {
        return view('frontend.sewa_mobil');
    });
    Route::get('mice', function () {
        return view('frontend.mice');
    });
    Route::get('mice_event', function () {
        return view('frontend.mice_event');
    });
});

resources/views/admin/tour_categori/form_categori.blade.php
@extends('admin.layouts.master')

@section('page_content')
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h4 class="mb-3 mb-md-0">Paket Wisata Management </h4>
        </div>
        <div class="d-flex align-items-center flex-wrap text-nowrap">
            {{--  --}}
        </div>
    </div>

    @include('admin.layouts.alert')
    <div class="row">
        <div class="col-md-12 grid-margin">
            <div class="card">
                <div class="card-header">
                    <div class="col-12 d-flex align-items-center">
                        <h4 class="card-title mb-0">
                            @if (@$edit_mode)
                                Edit Kategori wisata - {{ $categori->name }}
                            @else
                                Tambah Kategori wisata
                            @endif
                        </h4>
                    </div>
                </div>
                <div class="card-body">
                    <form
                        action="{{ @$edit_mode ? route('admin.tour_categori.update', ['tour_categori' => $categori->id]) : route('admin.tour_categori.store') }}"
                        enctype="multipart/form-data" method="POST">
                        @csrf
                        @if (@$edit_mode)
                            @method('PUT')
                        @endif
                        <div class="row">
                            <div class="col-md-8">
                                <div class="form-group @error('name') has-danger @enderror">
                                    <label class="control-label">Nama</label>
                                    <input type="text" name="name" class="form-control" placeholder="Masukkan nama"
                                        value="{{ @$edit_mode ? $categori->name : old('name') }}">
                                    @error('name')
                                        <label id="name-error" class="error mt-2 text-danger"
                                            for="name">{{ $message }}</label>
                                    @enderror
                                </div>
                                <div class="form-group @error('deskripsi') has-danger @enderror">
                                    <label class="control-label">Deskripsi</label>
                                    <input type="text" name="deskripsi" class="form-control" placeholder="Masukkan kode"
                                        value="{{ @$edit_mode ? $categori->deskripsi : old('deskripsi') }}">
                                    @error('deskripsi')
                                        <label id="deskripsi-error" class="error mt-2 text-danger"
                                            for="deskripsi">{{ $message }}</label>
                                    @enderror
                                </div>
                                <div class="form-group @error('price') has-danger @enderror">
                                    <label class="control-label">Harga Mulai</label>
                                    <input type="text" name="price" class="form-control"
                                        placeholder="Masukkan harga mulai"
                                        value="{{ @$edit_mode ? $categori->price : old('price') }}">
                                    @error('price')
                                        <label id="price-error" class="error mt-2 text-danger"
                                            for="price">{{ $message }}</label>
                                    @enderror
                                </div>
                                <div class="form-group @error('image') has-danger @enderror">
                                    <label>Image</label>
                                    <input type="file" class="use-dropify" name="image"
                                        data-default-file="{{ @$edit_mode ? asset('uploads/' . $categori->image) : '' }}">
                                    @error('image')
                                        <label id="image-error" class="error mt-2 text-danger"
                                            for="image">{{ $message }}</label>
                                    @enderror
                                </div>
                                <a href="{{ route('admin.tour_categori.index') }}"
                                    class="btn btn-secondary submit">Batal</a>
                                <button type="submit" class="btn btn-primary submit">Simpan</button>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
    @if (@$edit_mode)
        <div class="row">
            <div class="col-md-12 grid-margin">
                <h4>Manajemen Data Tour</h4>
                <hr>
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex justify-content-between align-items-baseline md-2">
                            <h6 class="card-title">Data Tour</h6>
                            <p><a href="{{ route('admin.tour_categori.create_tour', $categori->id) }}"
                                    class="btn btn-primary ">Tambah
                                    Tour</a></p>
                        </div>
                        <div class="table-responsive">
                            <table id="dataTableExample" class="table">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Name</th>
                                        <th>Image</th>
                                        <th>Harga Mulai</th>
                                        <th>Diskon</th>
                                        <th>Aksi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php $i=1 @endphp
                                    @foreach ($tour as $item)
                                        <tr>
                                            <td>{{ $i++ }}</td>
                                            <td>{{ $item->name }}</td>
                                            <td><img src="{{ asset('uploads/' . $item->image) }}" alt=""
                                                    class="img-fluid" width="100px"></td>
                                            <td>Rp. {{ number_format($item->start_price, 0, ',', '.') }}</td>
                                            <td>{{ $item->diskon }}%</td>
                                            <td align="right">

                                                <a href="{{ route('admin.tour_categori.edit_tour', $item->id) }}"
                                                    class="btn btn-info">Edit</a>

                                                <form action="{{ route('admin.tour_categori.destroy_tour', $item->id) }}"
                                                    method="POST" class="d-inline">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-danger show_confirm"
                                                        title='Delete' data-name="{{ $item->name }}">Delete</button>
                                                </form>

                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    @endif

@endsection

@section('include-css')
    <style type="text/css">
        .swal-modal {
            width: 300px;
            height: auto;
        }

        .swal-title {
            font-size: 18px;
        }

        .swal-footer {
            text-align: center;
        }
    </style>

    <link rel="stylesheet" href="{{ asset('vendors/dropify/dist/dropify.min.css') }}">
@endsection
@section('include-js')
    <script src="{{ asset('vendors/dropify/dist/dropify.min.js') }}"></script>
    <script>
        $(".use-dropify").dropify();
    </script>
    <script>
        $(function() {
            'use strict';

            $('#myDropify').dropify();
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
    <script type="text/javascript">
        $('.show_confirm').click(function(event) {
            var form = $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                    title: 'Anda yakin mau mengahapus data Tour "' + name + '" ?',
                    dangerMode: true,
                    buttons: {
                        confirm: {
                            text: 'Yes'
                        },
                        cancel: 'Cancel'

                    },
                })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });
    </script>
@endsection

resources/views/admin/tour_categori/index.blade.php
@extends('admin.layouts.master')
@section('page_content')
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h5 class="mb-2 mb-md-0">Manajmen Wisata</h5>
        </div>
    </div>
    @include('admin.layouts.alert')
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-baseline md-2">
                        <h6 class="card-title">Data Kategori Wisata</h6>
                        <p><a href="{{ route('admin.tour_categori.create') }}" class="btn btn-primary ">Tambah Kategori
                                Tour</a></p>
                    </div>
                    <div class="table-responsive">
                        <table id="dataTableExample" class="table">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Image</th>
                                    <th>Deskripsi</th>
                                    <th>Price</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php $i=1 @endphp
                                @foreach ($categories as $item)
                                    <tr>
                                        <td>{{ $i++ }}</td>
                                        <td>{{ $item->name }}</td>
                                        <td><img src="{{ asset('uploads/' . $item->image) }}" alt=""
                                                class="img-fluid" width="100px"></td>
                                        <td>{{ $item->deskripsi }}</td>
                                        <td>Rp. {{ number_format($item->price, 0, ',', '.') }}</td>
                                        <td align="right">

                                            <a href="{{ route('admin.tour_categori.edit', ['tour_categori' => $item->id]) }}"
                                                class="btn btn-info">Edit</a>

                                            <form
                                                action="{{ route('admin.tour_categori.destroy', ['tour_categori' => $item->id]) }}"
                                                method="POST" class="d-inline">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger show_confirm" title='Delete'
                                                    data-name="{{ $item->name }}">Delete</button>
                                            </form>

                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('include-css')
    <style type="text/css">
        .swal-modal {
            width: 300px;
            height: auto;
        }

        .swal-title {
            font-size: 18px;
        }

        .swal-footer {
            text-align: center;
        }
    </style>
@endsection
@section('include-js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
    <script type="text/javascript">
        $('.show_confirm').click(function(event) {
            var form = $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                    title: 'Anda yakin mau mengahapus data Kategori Tour "' + name + '" ?',
                    dangerMode: true,
                    buttons: {
                        confirm: {
                            text: 'Yes'
                        },
                        cancel: 'Cancel'

                    },
                })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });
    </script>
@endsection