routes/web.php
<?php

use App\Http\Controllers\AboutController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\BusController;
use App\Http\Controllers\CarsController;
use App\Http\Controllers\ConditionsController;
use App\Http\Controllers\GaleriController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KontakController;
use App\Http\Controllers\MicesController;
use App\Http\Controllers\MobilController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\TestimoniController;
use App\Http\Controllers\TourCategoriesController;
use App\Http\Controllers\WisataController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('sewa-mobil', [CarsController::class, 'mobil'])->name('sewa-mobil');
Route::get('sewa-bus', [MobilController::class, 'bus'])->name('sewa-bus');

Route::get('paket-wisata', [WisataController::class, 'index'])->name('paket-wisata');
Route::get('wisata/{slug}', [WisataController::class, 'wisata'])->name('wisata');
Route::get('detail-wisata/{slug}', [WisataController::class, 'detail_wisata'])->name('detail-wisata');

Route::get('mice', [MicesController::class, 'mice'])->name('mice');
Route::get('mice-event', [MicesController::class, 'mice_event'])->name('mice-event');

Route::get('blog', [BlogController::class, 'index'])->name('blog');
Route::get('detail-blog/{slug}', [BlogController::class, 'detail_blog'])->name('blog.detail-blog');
// Route::get('detail-blog', [BlogController::class, 'detail_blog'])->name('detail-blog');
Route::get('galeri', [GaleriController::class, 'galeri'])->name('galeri');
Route::get('about', [AboutController::class, 'index'])->name('about');
Route::get('kontak', [KontakController::class, 'index'])->name('kontak');

Route::get('login', [AuthController::class, 'index'])->name('login');
Route::get('register', [AuthController::class, 'register'])->name('register');
Route::post('proses_register', [AuthController::class, 'proses_register'])->name('proses_register');
Route::post('proses_login', [AuthController::class, 'proses_login'])->name('proses_login');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');

Route::get('/register/verify-email/{token}', [AuthController::class, 'verifyMail'])->name('verifyMail');
// Route::resource('admin/dashboard', DashboardController::class);

Route::group(['middleware' => ['auth']], function () {
    Route::prefix('admin/')->name('admin.')->middleware(['admin_role'])->group(function () {
        Route::get('create_tour/{id}', [TourCategoriesController::class, 'create_tour'])->name('tour_categori.create_tour');
        Route::resource('dashboard', DashboardController::class);
        Route::resource('user', UserController::class);
        Route::put('update-password/{userid}', [UserController::class, 'update_password'])->name('user.update-password');
        Route::resource('artikel', ArtikelController::class);
        Route::resource('galeri', GaleriController::class);
        Route::resource('condition', ConditionsController::class);
        Route::put('update_condition', [ConditionsController::class, 'update_condition'])->name('profil.update_condition');
        Route::resource('cars', CarsController::class);
        Route::resource('mobil', MobilController::class);
        Route::resource('profil', ProfilController::class);
        Route::put('update_profil', [ProfilController::class, 'update_profil'])->name('profil.update_profil');
        Route::resource('testimoni', TestimoniController::class);
        Route::resource('mice', MicesController::class);
        Route::put('update_mice', [MicesController::class, 'update_mice'])->name('mice.update_mice');
        Route::resource('tour_categori', TourCategoriesController::class);
        Route::post('store_tour/{id}', [TourCategoriesController::class, 'store_tour'])->name('tour_categori.store_tour');
        Route::get('edit_tour/{id}', [TourCategoriesController::class, 'edit_tour'])->name('tour_categori.edit_tour');
        Route::put('update_tour/{id}', [TourCategoriesController::class, 'update_tour'])->name('tour_categori.update_tour');
        Route::delete('destroy_tour/{id}', [TourCategoriesController::class, 'destroy_tour'])->name('tour_categori.destroy_tour');
        Route::get('destroy_price/{id}', [TourCategoriesController::class, 'destroy_price'])->name('tour_categori.destroy_price');
        Route::get('edit_price/{id}', [TourCategoriesController::class, 'edit_price'])->name('tour_categori.edit_price');
        Route::post('/update_price/{id}', [TourCategoriesController::class, 'update_price'])->name('tour_categori.update_price');
    });
});


Route::prefix('frontend/')->name('frontend.')->group(function () {
    Route::get('home', function () {
        return view('frontend.home');
    });
    Route::get('about', function () {
        return view('frontend.about');
    });
    Route::get('detail_blog', function () {
        return view('frontend.detail_blog');
    });
    Route::get('detail_wisata', function () {
        return view('frontend.detail_wisata');
    });
    Route::get('galeri', function () {
        return view('frontend.galeri');
    });
    Route::get('kontak', function () {
        return view('frontend.kontak');
    });
    Route::get('paket_wisata', function () {
        return view('frontend.paket_wisata');
    });
    Route::get('sewa_bus', function () {
        return view('frontend.sewa_bus');
    });
    Route::get('sewa_mobil', function () {
        return view('frontend.sewa_mobil');
    });
    Route::get('mice', function () {
        return view('frontend.mice');
    });
    Route::get('mice_event', function () {
        return view('frontend.mice_event');
    });
});

resources/views/admin/layouts/_footer.blade.php
<footer class="footer d-flex flex-column flex-md-row align-items-center justify-content-between">
    <p class="text-muted text-center text-md-left">Copyright © 2021 <a href="https://www.nobleui.com"
            target="_blank">NobleUI</a>. All rights reserved</p>
    <p class="text-muted text-center text-md-left mb-0 d-none d-md-block">Handcrafted With <i
            class="mb-1 text-primary ml-1 icon-small" data-feather="heart"></i></p>
</footer>

resources/views/admin/layouts/_navbar.blade.php
<nav class="navbar">
    <a href="#" class="sidebar-toggler">
        <i data-feather="menu"></i>
    </a>
    <div class="navbar-content">
        <ul class="navbar-nav">
            <li class="nav-item dropdown nav-profile">
                <a class="nav-link dropdown-toggle" href="#" id="profileDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{-- <img src="{{ Auth::user()->avatar }}" alt="profile"> --}}
                    <img src="{{ asset('uploads/' . Auth::user()->image) }}" alt="profile">
                </a>
                <div class="dropdown-menu" aria-labelledby="profileDropdown">
                    <div class="dropdown-header d-flex flex-column align-items-center">
                        <div class="figure mb-3">
                            {{-- <img src="{{ Auth::user()->avatar }}" alt=""> --}}
                            <img src="{{ asset('uploads/' . Auth::user()->image) }}" alt="">
                        </div>
                        <div class="info text-center">
                            <p class="name font-weight-bold mb-0">{{ Auth::user()->name }}</p>
                            <p class="email text-muted mb-3">{{ Auth::user()->email }}</p>
                        </div>
                    </div>
                    <div class="dropdown-body">
                        <ul class="profile-nav p-0 pt-3">
                            <li class="nav-item">
                                <a href="{{ url('admin/user/' . Auth::user()->id . '/edit') }}" class="nav-link">
                                    <i data-feather="edit"></i>
                                    <span>Edit Profile</span>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{{ url('logout') }}" class="nav-link">
                                    <i data-feather="log-out"></i>
                                    <span>Log Out</span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </li>
        </ul>
    </div>
</nav>

resources/views/admin/layouts/_sidebar.blade.php
<nav class="sidebar">
    <div class="sidebar-header">
        <a href="#" class="sidebar-brand">
            Noble<span>UI</span>
        </a>
        <div class="sidebar-toggler not-active">
            <span></span>
            <span></span>
            <span></span>
        </div>
    </div>
    <div class="sidebar-body">
        <ul class="nav">
            <li class="nav-item {{ Route::is('admin.dashboard.*') ? 'active' : '' }}">
                <a href="{{ route('admin.dashboard.index') }}" class="nav-link">
                    <i class="link-icon" data-feather="codesandbox"></i>
                    <span class="link-title">Dashboard</span>
                </a>
            </li>
            <li class="nav-item {{ Route::is('admin.user.*') ? 'active' : '' }}">
                <a href="{{ route('admin.user.index') }}" class="nav-link">
                    <i class="link-icon" data-feather="users"></i>
                    <span class="link-title">User</span>
                </a>
            </li>
            <li class="nav-item {{ Route::is('admin.profil.*') ? 'active' : '' }}">
                <a href="{{ route('admin.profil.index') }}" class="nav-link">
                    <i class="link-icon" data-feather="info"></i>
                    <span class="link-title">Profil</span>
                </a>
            </li>
            <li class="nav-item {{ Route::is('admin.tour_categori.*') ? 'active' : '' }}">
                <a href="{{ route('admin.tour_categori.index') }}" class="nav-link">
                    <i class="link-icon" data-feather="compass"></i>
                    <span class="link-title">Wisata</span>
                </a>
            </li>
            <li class="nav-item {{ Route::is('admin.mice.*') ? 'active' : '' }}">
                <a href="{{ route('admin.mice.index') }}" class="nav-link">
                    <i class="link-icon" data-feather="calendar"></i>
                    <span class="link-title">Mice</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#authPages" role="button" aria-expanded="false"
                    aria-controls="authPages">
                    <i class="link-icon" data-feather="truck"></i>
                    <span class="link-title">Trans</span>
                    <i class="link-arrow" data-feather="chevron-down"></i>
                </a>
                <div class="collapse" id="authPages">
                    <ul class="nav sub-menu">
                        <li class="nav-item {{ Route::is('admin.cars.*') ? 'active' : '' }}">
                            <a href="{{ route('admin.cars.index') }}" class="nav-link">
                                Mobil
                            </a>
                        </li>
                        <li class="nav-item {{ Route::is('admin.mobil.*') ? 'active' : '' }}">
                            <a href="{{ route('admin.mobil.index') }}" class="nav-link">
                                Bus
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" data-toggle="collapse" href="#authPages1" role="button" aria-expanded="false"
                    aria-controls="authPages1">
                    <i class="link-icon" data-feather="layout"></i>
                    <span class="link-title">Kontent</span>
                    <i class="link-arrow" data-feather="chevron-down"></i>
                </a>
                <div class="collapse" id="authPages1">
                    <ul class="nav sub-menu">
                        <li class="nav-item {{ Route::is('admin.galeri.*') ? 'active' : '' }}">
                            <a href="{{ route('admin.galeri.index') }}" class="nav-link">
                                {{-- <i class="link-icon" data-feather="image"></i> --}}
                                Galeri
                            </a>
                        </li>
                        <li class="nav-item {{ Route::is('admin.artikel.*') ? 'active' : '' }}">
                            <a href="{{ route('admin.artikel.index') }}" class="nav-link">
                                {{-- <i class="link-icon" data-feather="layout"></i> --}}
                                Artikel
                            </a>
                        </li>
                        <li class="nav-item {{ Route::is('admin.condition.*') ? 'active' : '' }}">
                            <a href="{{ route('admin.condition.index') }}" class="nav-link">
                                {{-- <i class="link-icon" data-feather="list"></i> --}}
                                Persyaratan
                            </a>
                        </li>
                        <li class="nav-item {{ Route::is('admin.testimoni.*') ? 'active' : '' }}">
                            <a href="{{ route('admin.testimoni.index') }}" class="nav-link">
                                {{-- <i class="link-icon" data-feather="smile"></i> --}}
                                Testimoni
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            {{-- <li class="nav-item {{ Route::is('admin.cars.*') ? 'active' : '' }}">
                <a href="{{ route('admin.cars.index') }}" class="nav-link">
                    <i class="link-icon" data-feather="truck"></i>
                    <span class="link-title">Mobil</span>
                </a>
            </li>
            <li class="nav-item {{ Route::is('admin.mobil.*') ? 'active' : '' }}">
                <a href="{{ route('admin.mobil.index') }}" class="nav-link">
                    <i class="link-icon" data-feather="truck"></i>
                    <span class="link-title">Bus</span>
                </a>
            </li> --}}
            <li class="nav-item">
                <a href="{{ asset('assets/manual_book.pdf') }}" class="nav-link">
                    <i class="link-icon" data-feather="file-text"></i>
                    <span class="link-title">Manual Book</span>
                </a>
            </li>

        </ul>
    </div>
</nav>

resources/views/admin/layouts/alert.blade.php
@if (Session::has('notif'))
    @php
        if (Session::get('notif_status') == '1') {
            $notif_class = 'success';
        } elseif (Session::get('notif_status') == '0') {
            $notif_class = 'danger';
        } else {
            $notif_class = 'warning';
        }
    @endphp
    <div class="alert alert-fill-{{ $notif_class }}" role="alert">
        {{ Session::get('notif') }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
    </div>
@endif
{{-- @if ($errors->any())
    <div class="alert alert-fill-danger" role="alert">
        <ul>
            @foreach ($errors->all() as $error)
                <li>
                    {{ $error }}
                </li>
            @endforeach
        </ul>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                aria-hidden="true">&times;</span></button>
    </div>
@endif --}}

resources/views/admin/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ @$page_title ? $page_title . ' - ' . config('app.name') : config('app.name') }}</title>
    <!-- core:css -->
    <link rel="shortcut icon" href="{{ asset('images/favicon.png') }}" />
    <link rel="stylesheet" href="{{ asset('vendors/core/core.css') }}">
    <!-- endinject -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <!-- plugin css for this page -->
    <link rel="stylesheet" href="{{ asset('vendors/datatables.net-bs4/dataTables.bootstrap4.css') }}">
    <!-- end plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="{{ asset('fonts/feather-font/css/iconfont.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/flag-icon-css/css/flag-icon.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/bootstrap-datepicker/bootstrap-datepicker.min.css') }}">
    <link rel="stylesheet" href="{{ asset('vendors/fullcalendar/main.min.css') }}">

    <!-- endinject -->
    <!-- Layout styles -->
    <!-- End layout styles -->

    @yield('dt')
    <link rel="stylesheet" type="text/css"
        href="https://cdn.datatables.net/v/bs4/dt-1.11.3/af-2.3.7/b-2.0.1/date-1.1.1/sb-1.2.2/datatables.min.css" />
    {{-- style data table --}}
    <!-- endinject -->
    @yield('include-css')
    <link rel="stylesheet" href="{{ asset('css/demo_1/style.css') }}">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Layout styles -->
</head>

<body class="sidebar-dark">
    <div class="main-wrapper">
        <!-- partial:partials/_sidebar.html -->
        @include('admin.layouts._sidebar')
        <!-- partial -->

        <div class="page-wrapper">

            <!-- partial:partials/_navbar.html -->
            @include('admin.layouts._navbar')

            <!-- partial -->
            <div class="page-content">
                @yield('page_content')
            </div>

            <!-- partial:partials/_footer.html -->
            @include('admin.layouts._footer')
            <!-- partial -->

        </div>
    </div>

    @yield('modals')

    <!-- core:js -->
    <script src="{{ asset('vendors/core/core.js') }}"></script>
    <script src="{{ asset('vendors/bootstrap-datepicker/bootstrap-datepicker.min.js') }}"></script>
    <!-- endinject -->
    <script src="{{ asset('vendors/datatables.net/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('vendors/datatables.net-bs4/dataTables.bootstrap4.js') }}"></script>
    <script src="{{ asset('vendors/fullcalendar/main.min.js') }}"></script>
    <!-- endinject -->
    <!-- inject:js -->
    <script src="{{ asset('vendors/feather-icons/feather.min.js') }}"></script>
    <script src="{{ asset('js/template.js') }}"></script>
    <script src="{{ asset('js/datepicker.js') }}"></script>
    <!-- endinject -->
    <script src="{{ asset('js/data-table.js') }}"></script>
    @yield('include-js')
    <script type="text/javascript"
        src="https://cdn.datatables.net/v/bs4/dt-1.11.3/af-2.3.7/b-2.0.1/date-1.1.1/sb-1.2.2/datatables.min.js"></script>
    <!-- end custom js for this page -->

    <!-- ini js data table -->
    @yield('dt')
    <!-- endinject -->
</body>

</html>