routes/web.php
<?php

use App\Http\Controllers\AboutController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ArtikelController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\BusController;
use App\Http\Controllers\CarsController;
use App\Http\Controllers\ConditionsController;
use App\Http\Controllers\GaleriController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\KontakController;
use App\Http\Controllers\MicesController;
use App\Http\Controllers\MobilController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\TestimoniController;
use App\Http\Controllers\TourCategoriesController;
use App\Http\Controllers\WisataController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });
Route::get('/', [HomeController::class, 'index'])->name('index');
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('sewa-mobil', [CarsController::class, 'mobil'])->name('sewa-mobil');
Route::get('sewa-bus', [MobilController::class, 'bus'])->name('sewa-bus');

Route::get('paket-wisata', [WisataController::class, 'index'])->name('paket-wisata');
Route::get('wisata/{slug}', [WisataController::class, 'wisata'])->name('wisata');
Route::get('detail-wisata/{slug}', [WisataController::class, 'detail_wisata'])->name('detail-wisata');

Route::get('mice', [MicesController::class, 'mice'])->name('mice');
Route::get('mice-event', [MicesController::class, 'mice_event'])->name('mice-event');

Route::get('blog', [BlogController::class, 'index'])->name('blog');
Route::get('detail-blog/{slug}', [BlogController::class, 'detail_blog'])->name('blog.detail-blog');
// Route::get('detail-blog', [BlogController::class, 'detail_blog'])->name('detail-blog');
Route::get('galeri', [GaleriController::class, 'galeri'])->name('galeri');
Route::get('about', [AboutController::class, 'index'])->name('about');
Route::get('kontak', [KontakController::class, 'index'])->name('kontak');

Route::get('login', [AuthController::class, 'index'])->name('login');
Route::get('register', [AuthController::class, 'register'])->name('register');
Route::post('proses_register', [AuthController::class, 'proses_register'])->name('proses_register');
Route::post('proses_login', [AuthController::class, 'proses_login'])->name('proses_login');
Route::get('logout', [AuthController::class, 'logout'])->name('logout');

Route::get('/register/verify-email/{token}', [AuthController::class, 'verifyMail'])->name('verifyMail');
// Route::resource('admin/dashboard', DashboardController::class);

Route::group(['middleware' => ['auth']], function () {
    Route::prefix('admin/')->name('admin.')->middleware(['admin_role'])->group(function () {
        Route::get('create_tour/{id}', [TourCategoriesController::class, 'create_tour'])->name('tour_categori.create_tour');
        Route::resource('dashboard', DashboardController::class);
        Route::resource('user', UserController::class);
        Route::put('update-password/{userid}', [UserController::class, 'update_password'])->name('user.update-password');
        Route::resource('artikel', ArtikelController::class);
        Route::resource('galeri', GaleriController::class);
        Route::resource('condition', ConditionsController::class);
        Route::put('update_condition', [ConditionsController::class, 'update_condition'])->name('profil.update_condition');
        Route::resource('cars', CarsController::class);
        Route::resource('mobil', MobilController::class);
        Route::resource('profil', ProfilController::class);
        Route::put('update_profil', [ProfilController::class, 'update_profil'])->name('profil.update_profil');
        Route::resource('testimoni', TestimoniController::class);
        Route::resource('mice', MicesController::class);
        Route::put('update_mice', [MicesController::class, 'update_mice'])->name('mice.update_mice');
        Route::resource('tour_categori', TourCategoriesController::class);
        Route::post('store_tour/{id}', [TourCategoriesController::class, 'store_tour'])->name('tour_categori.store_tour');
        Route::get('edit_tour/{id}', [TourCategoriesController::class, 'edit_tour'])->name('tour_categori.edit_tour');
        Route::put('update_tour/{id}', [TourCategoriesController::class, 'update_tour'])->name('tour_categori.update_tour');
        Route::delete('destroy_tour/{id}', [TourCategoriesController::class, 'destroy_tour'])->name('tour_categori.destroy_tour');
        Route::get('destroy_price/{id}', [TourCategoriesController::class, 'destroy_price'])->name('tour_categori.destroy_price');
        Route::get('edit_price/{id}', [TourCategoriesController::class, 'edit_price'])->name('tour_categori.edit_price');
        Route::post('/update_price/{id}', [TourCategoriesController::class, 'update_price'])->name('tour_categori.update_price');
    });
});


Route::prefix('frontend/')->name('frontend.')->group(function () {
    Route::get('home', function () {
        return view('frontend.home');
    });
    Route::get('about', function () {
        return view('frontend.about');
    });
    Route::get('detail_blog', function () {
        return view('frontend.detail_blog');
    });
    Route::get('detail_wisata', function () {
        return view('frontend.detail_wisata');
    });
    Route::get('galeri', function () {
        return view('frontend.galeri');
    });
    Route::get('kontak', function () {
        return view('frontend.kontak');
    });
    Route::get('paket_wisata', function () {
        return view('frontend.paket_wisata');
    });
    Route::get('sewa_bus', function () {
        return view('frontend.sewa_bus');
    });
    Route::get('sewa_mobil', function () {
        return view('frontend.sewa_mobil');
    });
    Route::get('mice', function () {
        return view('frontend.mice');
    });
    Route::get('mice_event', function () {
        return view('frontend.mice_event');
    });
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'role',
        'no_hp',
        'password',
        'email_verify_at',
        'token',
        'image',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\user;

use Illuminate\Http\Request;
use Validator;
use File;
use Storage;
use Hash;
use Illuminate\Support\Str;

use Illuminate\Database\Eloquent\Builder;
use App\Http\Controllers\Controller;


class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::all();
        // dd($user->toArray());
        $data['page_title'] = 'Manajemen User';
        $data['users'] = $user;
        return view('admin.user.index', $data);
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $data['page_title'] = 'Tambah user';
        $data['edit_password'] = true;
        return view('admin.user.form_user', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $rules = array(
            'name' => 'required',
            'no_hp' => 'required',
            'email' => 'required',
            'password' => 'required',
            'image' => 'required|file|mimes:jpg,png',
        );
        $validator = Validator::make($request->all(), $rules, $messages = [
            'required' => 'The :attribute field is required.',
            'file' => 'The :attribute must be a file.',
            'mimes' => 'The :attribute must be a file of type: :values.',
        ]);

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->with(['notif_status' => '0', 'notif' => 'Insert data failed.'])
                ->withInput();
        }
        $token = Str::random(60);
        $object = array(
            'name' => $request->name,
            'email' => $request->email,
            'role' => 'admin',
            'no_hp' => $request->no_hp,
            'password' => Hash::make($request->password),
            'token' => $token,
        );


        if ($request->has('image')) {
            $image = Storage::disk('uploads')->put('user', $request->image);
            $object['image'] = $image;
            // dd($object['image']);
        }

        User::create($object);
        return redirect()->route('admin.user.index')
            ->with(['notif_status' => '1', 'notif' => 'Insert data succed.']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $user = User::find($id);
        $data['page_title'] = 'Edit User';
        $data['user'] = $user;
        $data['edit_mode'] = true;
        $data['edit_password'] = false;
        return view('admin.user.form_user', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $rules = array(
            'name' => 'required',
            'email' => 'required',
            'no_hp' => 'required',
            'avatar' => 'file|mimes:jpg,png',
        );
        // dd($rules);
        $validator = Validator::make($request->all(), $rules, $messages = [
            'mimes' => 'The :attribute must be a file of type: :values.',
            'required' => 'The :attribute field is required.'
        ]);

        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->with(['notif_status' => '0', 'notif' => 'Insert data failed.'])
                ->withInput();
        }
        $object = array(
            'name' => $request->name,
            'email' => $request->email,
            'no_hp' => $request->no_hp,
        );

        $current = user::findOrFail($id);

        if ($request->has('image')) {
            $image = Storage::disk('uploads')->put('user', $request->image);
            $object['image'] = $image;
            // dd($object['avatar']);
            if ($current->image) {
                File::delete('./uploads/' . $current->image);
            }
        }

        $current->update($object);
        return redirect()->route('admin.user.index')
            ->with(['notif_status' => '1', 'notif' => 'Update data succeed.']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update_password(Request $request, $id)
    {
        $rules = [
            'new_password' => 'required|min:8',
            'password_confirmation' => 'required|same:new_password',
        ];
        $validator = Validator::make($request->all(), $rules,  $messages = [
            'required' => 'The :attribute field is required.',
            'min' => 'the :attribute field is required 8 characters.',
        ]);
        if ($validator->fails()) {
            return redirect()->back()
                ->withErrors($validator)
                ->withInput();
        }

        $data = User::find($id);
        $data->password = Hash::make($request->new_password);
        $data->save();

        return redirect()->route('admin.user.index')->with(['notif_status' => '1', 'notif' => 'Update data succeed.']);
    }

    public function destroy($id)
    {
        //
        $user = user::where('id', $id)->firstOrFail();
        File::delete('./uploads/' . $user->image);
        $user->delete();
        return redirect()->route('admin.user.index')
            ->with(['notif_status' => '1', 'notif' => 'Delete data succeed.']);
    }
}

resources/views/admin/user/form_user.blade.php
@extends('admin.layouts.master')

@section('page_content')
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h4 class="mb-3 mb-md-0">User Management </h4>
        </div>
        <div class="d-flex align-items-center flex-wrap text-nowrap">
            {{--  --}}
        </div>
    </div>

    @include('admin.layouts.alert')
    <div class="row">
        <div class="col-md-12 grid-margin">
            <div class="card">
                <div class="card-header">
                    <div class="col-12 d-flex align-items-center">
                        <h4 class="card-title mb-0">
                            @if (@$edit_mode)
                                Edit user - {{ $user->name }}
                            @else
                                Tambah user
                            @endif
                        </h4>
                    </div>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <form
                                action="{{ @$edit_mode ? route('admin.user.update', ['user' => $user->id]) : route('admin.user.store') }}"
                                enctype="multipart/form-data" method="POST">
                                @csrf
                                @if (@$edit_mode)
                                    @method('PUT')
                                @endif
                                <div class="form-group @error('name') has-danger @enderror">
                                    <label class="control-label">Nama</label>
                                    <input type="text" name="name" class="form-control" placeholder="Enter Nama "
                                        value="{{ @$edit_mode ? $user->name : old('name') }}">
                                    @error('name')
                                        <label id="name-error" class="error mt-2 text-danger"
                                            for="name">{{ $message }}</label>
                                    @enderror
                                </div>
                                <div class="form-group @error('email') has-danger @enderror">
                                    <label class="control-label">Email</label>
                                    <input type="email" name="email" class="form-control" placeholder="Enter Nama "
                                        value="{{ @$edit_mode ? $user->email : old('email') }}">
                                    @error('email')
                                        <label id="email-error" class="error mt-2 text-danger"
                                            for="email">{{ $message }}</label>
                                    @enderror
                                </div>
                                {{-- <div class="form-group @error('email') has-danger @enderror">
                                    <label class="control-label">Role</label>
                                    <select name="role" class="form-control">
                                        <option value=" "> -- role -- </option>
                                        <option value="admin"{{ @$edit_mode ? $user->role == 'admin' ? 'selected' : '' }}>admin</option>
                                    </select>
                                    @error('role')
                                        <label id="role-error" class="error mt-2 text-danger"
                                            for="role">{{ $message }}</label>
                                    @enderror
                                </div> --}}
                                <div class="form-group @error('no_hp') has-danger @enderror">
                                    <label class="control-label">No Hp</label>
                                    <input type="text" name="no_hp" class="form-control" placeholder="Enter Nama "
                                        value="{{ @$edit_mode ? $user->no_hp : old('no_hp') }}">
                                    @error('no_hp')
                                        <label id="no_hp-error" class="error mt-2 text-danger"
                                            for="no_hp">{{ $message }}</label>
                                    @enderror
                                </div>
                                @if (@$edit_password)
                                    <div class="form-group @error('password') has-danger @enderror">
                                        <label class="control-label">Password</label>
                                        <input type="password" name="password" class="form-control"
                                            placeholder="Enter Nama "
                                            value="{{ @$edit_mode ? $user->password : old('password') }}">
                                        @error('password')
                                            <label id="password-error" class="error mt-2 text-danger"
                                                for="password">{{ $message }}</label>
                                        @enderror
                                    </div>
                                @endif
                                <div class="form-group @error('image') has-danger @enderror">
                                    <label>Image</label>
                                    <input type="file" class="use-dropify" name="image"
                                        data-default-file="{{ @$edit_mode ? asset('uploads/' . $user->image) : '' }}">
                                    @error('image')
                                        <label id="image-error" class="error mt-2 text-danger"
                                            for="image">{{ $message }}</label>
                                    @enderror
                                </div><br />
                                <a href="{{ route('admin.user.index') }}" class="btn btn-secondary submit">Batal</a>
                                <button type="submit" class="btn btn-primary submit">Simpan</button>
                            </form>
                        </div>
                        @if (@$edit_mode)
                            <div class="col-md-4">
                                <div class="card">
                                    <div class="card-header">
                                        <div class="col-12 d-flex align-items-center">
                                            <h4 class="card-title mb-0">Reset Password</h4>
                                        </div>
                                    </div>
                                    <div class="card-body">
                                        <form method="POST" action="{{ route('admin.user.update-password', $user->id) }}">
                                            @csrf
                                            @method('PUT')
                                            <div class="form-group @error('new_password') has-danger @enderror">
                                                <label class="control-label">Password</label>
                                                <div class="input-group mb-3">
                                                    <input type="password" class="form-control" id="password"
                                                        name="new_password" placeholder="Masukkan password baru Anda">
                                                    <div class="input-group-append">
                                                        <button class="btn form-control btn-outline-secondary"
                                                            type="button" onclick="change_password()" id="button-addon2"><i
                                                                class="fa fa-eye" id="icons"></i></button>
                                                    </div>
                                                </div>
                                                @error('new_password')
                                                    <label id="new_password-error" class="error mt-2 text-danger"
                                                        for="new_password">{{ $message }}</label>
                                                @enderror
                                            </div>
                                            <div class="form-group @error('password_confirmation') has-danger @enderror">
                                                <label class="control-label">Password</label>
                                                <div class="input-group mb-3">
                                                    <input type="password" class="form-control" id="password-confirm"
                                                        name="password_confirmation"
                                                        placeholder="Masukkan confirmasi password Anda">
                                                </div>
                                                @error('password_confirmation')
                                                    <label id="password_confirmation-error" class="error mt-2 text-danger"
                                                        for="password_confirmation">{{ $message }}</label>
                                                @enderror
                                            </div>
                                            <div class="form-group mt-2 mb-0">
                                                <button type="submit" class="btn btn-primary">Simpan</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        @endif
                    </div>

                </div>
            </div>
        </div>
    </div> <!-- row -->
@endsection

@section('include-css')
    <link rel="stylesheet" href="{{ asset('vendors/dropify/dist/dropify.min.css') }}">
    <style type="text/css">
        .swal-modal {
            width: 300px;
            height: auto;
        }

        .swal-title {
            font-size: 18px;
        }

        .swal-footer {
            text-align: center;
        }
    </style>
@endsection

@section('include-js')
    <script src="{{ asset('vendors/dropify/dist/dropify.min.js') }}"></script>
    <script>
        $(".use-dropify").dropify();
    </script>
    <script>
        $(function() {
            'use strict';

            $('#myDropify').dropify();
        });
    </script>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.master')
@section('page_content')
    <div class="d-flex justify-content-between align-items-center flex-wrap grid-margin">
        <div>
            <h5 class="mb-2 mb-md-0">Manajmen User</h5>
        </div>
    </div>
    @include('admin.layouts.alert')
    <div class="row">
        <div class="col-md-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-baseline md-2">
                        <h6 class="card-title">Data User</h6>
                        <p><a href="{{ route('admin.user.create') }}" class="btn btn-primary ">Tambah User</a></p>
                    </div>
                    <div class="table-responsive">
                        <table id="dataTableExample" class="table">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Name</th>
                                    <th>Avatar</th>
                                    <th>Email</th>
                                    <th>No hp</th>
                                    <th>Role</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                                @php $i=1 @endphp
                                @foreach ($users as $item)
                                    <tr>
                                        <td>{{ $i++ }}</td>
                                        <td>{{ $item->name }}</td>
                                        <td><img src="{{ asset('uploads/' . $item->image) }}" alt=""
                                                class="img-fluid" width="100px"></td>
                                        <td>{{ $item->email }}</td>
                                        <td>{{ $item->no_hp }}</td>
                                        <td>{{ $item->role }}</td>
                                        <td align="right">

                                            <a href="{{ route('admin.user.edit', ['user' => $item->id]) }}"
                                                class="btn btn-info">Edit</a>

                                            <form action="{{ route('admin.user.destroy', ['user' => $item->id]) }}"
                                                method="POST" class="d-inline">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger show_confirm" title='Delete'
                                                    data-name="{{ $item->name }}">Delete</button>
                                            </form>

                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('include-css')
    <style type="text/css">
        .swal-modal {
            width: 300px;
            height: auto;
        }

        .swal-title {
            font-size: 18px;
        }

        .swal-footer {
            text-align: center;
        }
    </style>
@endsection
@section('include-js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
    <script type="text/javascript">
        $('.show_confirm').click(function(event) {
            var form = $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                    title: 'Anda yakin mau mengahapus data Font "' + name + '" ?',
                    dangerMode: true,
                    buttons: {
                        confirm: {
                            text: 'Yes'
                        },
                        cancel: 'Cancel'

                    },
                })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });
    </script>
@endsection